server:
  port: 9004

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-auth-db:5432/auth_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        time_zone: Asia/Ho_Chi_Minh

eureka:
  instance:
    hostname: auth-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}
