spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://postgres-task-db:5432/task_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9007

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

# THÊM DÒNG NÀY
jwt:
  secret: ${JWT_SECRET}

vapid:
  public:
    key: ${VAPID_PUBLIC_KEY}
  private:
    key: ${VAPID_PRIVATE_KEY}