spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://postgres-task-db:5432/task_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: 9007

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

eureka:
  instance:
    hostname: task-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}

vapid:
  public:
    key: ${VAPID_PUBLIC_KEY:}
  private:
    key: ${VAPID_PRIVATE_KEY:}
